name: Firebase Deployment
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: Install Dependencies & Build Astro
        run: |
          npm install
          npm run build
      - name: Create & Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Verify Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist     
      - name: Firebase Production Deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIUM95 }}'
          channelId: live
          projectId: pium95
