name: Firebase Deployment
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g yarn
      - name: Yarn Install, Build and Test
        run: |
          yarn install
          yarn build
      - name: Create & Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build 
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:   
      - name: Firebase Production Deployment
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PIUM95 }}'
          channelId: live
          projectId: pium95
